# MySQL.  Versions 4.1 and 5.0 are recommended.
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test
  pool: 5
  username: root
  password:
  host: 0.0.0.0

cucumber: *test
cypress: *test
