version: v1.0
name: ''
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
test: &ref_0
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test
  pool: 5
  username: root
  password: null
  host: 0.0.0.0
cucumber: *ref_0
blocks: []
